Repository theforeman/foreman-installer, pull requests merged in 2018-04, with the labels that each got.

#266 Add a rake task to pin modules to released versions
  .gitignore
  Gemfile
  Rakefile
Labels: Needs testing

#267 Fixes #23030 - Add SCL Mongo Hiera
  config/foreman-hiera.conf
  config/foreman.hiera/mongo-RedHat-7.yaml
Labels: Needs re-review, Needs testing

#270 Fixes #23242 - Add cli plugins to answer file
  config/foreman-answers.yaml
Labels: Needs testing, Waiting on contributor

#269 Refs #22513 - Allow overriding postgresql server settings via hiera
  Puppetfile
  config/foreman.hiera/custom.yaml
Labels: Needs testing
