Repository theforeman/foreman-installer, pull requests merged in 2019-07, with the labels that each got.

#369 Allow easy branding of the foreman-proxy-certs-genereate tool
  katello_certs/hooks/boot/02-message-helpers.rb
Labels: Needs testing

#370 Fixes #27197 - check uppercase env vars
  checks/env_variables.rb
Labels: Needs testing, Waiting on contributor

#371 Fixes #27262 - Add virt_who plugins to katello
  config/katello-answers.yaml
  config/katello.migrations/190710133444-add-virt-who.rb
Labels: Needs testing

#372 Fixes #27269 - force no_prefix to false for f-proxy-content
  config/foreman-proxy-content.migrations/190710195757-force_no_prefix_false.rb
Labels: Needs testing

#347 Fixes #25564 - addedTargetOption
  bin/katello-certs-check
  spec/fixtures/katello-certs-check/missing-parameter.txt
Labels: Needs testing

#373 Fixes #27314 mongoDB engine upgrade from MMAPv1 to WiredTiger space
  katello/hooks/pre_validations/30-mongo_storage_engine.rb
Labels: Needs testing, Not yet reviewed

#374 Fixes #27357 - properly check for katello scenario
  katello/hooks/pre_validations/30-mongo_storage_engine.rb
Labels: Needs testing

#375 Fixes #27424 - Ensure DB is seeded
  katello/hooks/post/30-upgrade.rb
Labels: Needs testing, Waiting on contributor

#378 Pin modules for Foreman 1.23
  .gitignore
  Puppetfile
  Puppetfile.lock
Labels: Needs testing, Not yet reviewed
