Repository theforeman/foreman-installer, pull requests merged in 2019-01, with the labels that each got.

#296 Refs #25170 - Add migration for new seed param naming.
  config/foreman.migrations/20181015123542_migrate_seed_params.rb
Labels: Needs testing, Waiting on contributor

#310 Refs #25170 - Use new parameter names in post install
  hooks/post/10-post_install_message.rb
  katello/hooks/boot/02-message-helpers.rb
Labels: Needs testing

#311 Refs #25839 - Avoid storing puppetserver related versions
  config/foreman-proxy-content.migrations/190111131058-reset-puppetserver-versions.rb
  config/foreman.migrations/20190111131058-reset-puppetserver-versions.rb
  config/katello.migrations/190111131058-reset-puppetserver-versions.rb
  katello/hooks/pre_validations/31-upgrade-puppet.rb
Labels: Needs testing

#313 Refs #25839 - Use the correct variable
  config/foreman-proxy-content.migrations/190111131058-reset-puppetserver-versions.rb
  config/katello.migrations/190111131058-reset-puppetserver-versions.rb
Labels: Needs testing

#315 Rename katello-certs directory
  Rakefile
  bin/foreman-proxy-certs-generate
  katello_certs/config/foreman-proxy-certs-answers.yaml
  katello_certs/config/foreman-proxy-certs.yaml
Labels: Needs testing, Not yet reviewed

#316 Refs #25839 - Use the correct variable
  config/foreman.migrations/20190111131058_reset_puppetserver_versions.rb
Labels: Needs testing

#317 Fixes #25951 - always print the credentials after install
  hooks/post/10-post_install_message.rb
Labels: Needs testing
