Repository theforeman/foreman-installer, pull requests merged in 2020-07, with the labels that each got.

#535 Update modules for Foreman 2.1.0
  Puppetfile
  Puppetfile.lock
Labels: Needs testing

#510 Fixes #29963 - Manage services without foreman-maintain
  hooks/boot/03-foreman-maintain-extensions.rb
  hooks/boot/04-services.rb
  spec/services_hook_extensions_spec.rb
Labels: Needs testing, Not yet reviewed

#509 Fixes #29797 - Merge --reset-foreman-db and --reset into --reset-data
  hooks/boot/01-kafo-hook-extensions.rb
  hooks/boot/10-reset_data.rb
  hooks/boot/10-reset_foreman_db.rb
  hooks/pre/10-reset_data.rb
  hooks/pre/10-reset_foreman_db.rb
  katello/hooks/pre/10-reset_feature.rb
Labels: Needs re-review, Needs testing

#541 Fixes #29296 - remove --upgrade
  katello/hooks/boot/30-upgrade.rb
  katello/hooks/pre_validations/29-upgrade.rb
Labels: Needs testing

#544 Fixes #30506: Ensure selinux packages are installed before puppet run
  hooks/boot/01-kafo-hook-extensions.rb
  hooks/pre/31_install_scl_packages.rb
  hooks/pre/32-install_selinux_packages.rb
Labels: Needs testing

#545 Refs #30506: Check modern selinux enabled fact
  hooks/pre/32-install_selinux_packages.rb
Labels: Needs testing

#547 Refs #30506: Install crane-selinux if pulp enabled
  hooks/pre/32-install_selinux_packages.rb
Labels: Needs testing
