Repository theforeman/foreman-installer, pull requests merged in 2021-07, with the labels that each got.

#693 Fixes #32916 - add scenario overrides
  config/foreman-hiera.yaml
Labels: Needs testing

#694 Fixes #32916 - add scenario overrides
  config/foreman-hiera.yaml
Labels: Needs testing

#690 Fixes #32885: Remove puppet from foreman::user_groups if present
  config/foreman.migrations/20210625142707_dynamic_puppet_in_foreman_groups.rb
  config/katello-answers.yaml
  config/katello.migrations/190314163941-remove-foreman-user-groups.rb
  config/katello.migrations/210625142712-dynamic-puppet-in-foreman-groups.rb
  spec/fixtures/cleanup-foreman-user-groups/foreman-answers-after.yaml
  spec/fixtures/cleanup-foreman-user-groups/foreman-answers-before.yaml
  spec/fixtures/cleanup-foreman-user-groups/katello-answers-after.yaml
  spec/fixtures/cleanup-foreman-user-groups/katello-answers-before.yaml
  spec/migration_spec.rb
Labels: Needs re-review, Needs testing

#696 2.5 puppet module updates for Pulp 3.14
  Puppetfile
  Puppetfile.lock
Labels: Needs testing

#697 Fixes #32532: Ensure a valid tuning option is supplied
  Gemfile
  hooks/boot/13-tuning.rb
  hooks/pre_commit/13-tuning.rb
Labels: Needs testing

#695 Refs #32914: Add migrations for foreman_puppet plugin
  config/foreman-answers.yaml
  config/foreman.migrations/20210708144320_add_foreman_puppet.rb
  config/katello-answers.yaml
  config/katello.migrations/210708144422-add-foreman-puppet.rb
  spec/fixtures/pulpcore-migration-dont-use-content-plugins-on-upgrades/katello-answers-after.yaml
  spec/fixtures/pulpcore-migration-rpm-only/katello-answers-after.yaml
  spec/fixtures/pulpcore-migration/katello-answers-after.yaml
Labels: Needs testing

#699 Replace all dash/underscores in create-migration
  bin/create-migration
Labels: Needs testing, Not yet reviewed

#701 Do not pass --assumeyes to f-maintain packages is-locked
  hooks/pre_commit/09-version_locking.rb
Labels: Needs testing

#705 Add ACD plugin
  config/foreman-answers.yaml
  config/foreman-proxy-content-answers.yaml
  config/foreman-proxy-content.migrations/20210729084840-add-proxy-acd-plugin.rb
  config/foreman.migrations/20210729084840_add_acd_plugin.rb
  config/katello-answers.yaml
  config/katello.migrations/20210729084840_add_acd_plugin.rb
  spec/fixtures/pulpcore-migration-dont-use-content-plugins-on-upgrades/katello-answers-after.yaml
  spec/fixtures/pulpcore-migration-rpm-only/katello-answers-after.yaml
  spec/fixtures/pulpcore-migration/katello-answers-after.yaml
Labels: Needs re-review, Needs testing
