Repository theforeman/foreman-installer, pull requests merged in 2022-02, with the labels that each got.

#740 Change puppet::server_envs_dir to Array data type
  config/foreman-proxy-content.migrations/220204223518-puppet-multiple-env-paths.rb
  config/foreman.migrations/20220204223518_puppet_multiple_env_paths.rb
  config/katello.migrations/220204223518-puppet-multiple-env-paths.rb
Labels: Needs testing, Not yet reviewed

#741 Refs #34189 - update certs and katello for FIPS
  Puppetfile
  Puppetfile.lock
Labels: Needs testing

#742 Pin modules for 3.2 branching
  Puppetfile
  Puppetfile.lock
Labels: Needs testing

#744 Fixes #34440 - skip upgrade:run by run_rake_upgrade=false
  hooks/post/30-upgrade.rb
Labels: Needs testing

#745 Fixes #34440 - skip upgrade:run by run_rake_upgrade=false
  hooks/post/30-upgrade.rb
Labels: Needs testing

#746 Fixes #34440 - skip upgrade:run by run_rake_upgrade=false
  hooks/post/30-upgrade.rb
Labels: Needs testing

#747 Fixes #34379 - Update pulpcore to create a system group
  Puppetfile.lock
Labels: Needs testing

#748 Refs #34394 - include new puppet-foreman for dynflow restart
  Puppetfile
  Puppetfile.lock
Labels: Needs testing, Waiting on contributor

#749 Refs #34394 - include new puppet-foreman for dynflow restart
  Puppetfile
  Puppetfile.lock
Labels: Needs testing, Waiting on contributor

#751 Fixes #33808 - Release 3.0.2
  Puppetfile.lock
  VERSION
Labels: Needs testing
