Repository theforeman/foreman-installer, pull requests merged in 2024-11, with the labels that each got.

#992 Bump develop to 3.14.0-develop
  VERSION
Labels: Not yet reviewed

#997 [3.11] Revert "Fixes #37828: Ignore system CA trust when verifying certificates"
  bin/katello-certs-check
Labels: Stable branch

#998 Fixes #38010 - Update katello/certs for OpenJDK 17 compatibility
  Puppetfile
  Puppetfile.lock
Labels: Stable branch

#993 Refs #37803 - Remove ProxyCommand option from Ansible options
  config/foreman.migrations/20241106161211_remove_proxycommand.rb
Labels: Needs re-review

#1001 Refs #37803 - Remove ProxyCommand option from Ansible options
  config/foreman.migrations/20241106161211_remove_proxycommand.rb
Labels: Stable branch

#1002 Drop EL 8 from Packit config
  .packit.yaml
Labels: Stable branch
